name: Condition Test Workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Trigger Workflow"]
    types:
      - completed

jobs:
  first_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        should_fail: [false, true]
    continue-on-error: true
    steps:
      - name: Echo matrix value
        run: echo "This matrix job should_fail=${{ matrix.should_fail }}"
      - name: Pass or fail
        run: |
          if [ "${{ matrix.should_fail }}" = "true" ]; then
            echo "This job is designed to fail."
            exit 1
          else
            echo "This job is designed to pass."
          fi

  second_job_with_condition:
    needs: first_job
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Run if condition is met
        run: |
            echo "Second job with full condition completed."
            echo "Outcome: ${{ steps.first_job.outcome }}"

  fail_workflow_run_if_tests_failed:
    needs: first_job
    runs-on: ubuntu-latest
    if: needs.first_job.result == 'failure' ||
        needs.first_job.result == 'cancelled' ||
        needs.first_job.result == 'skipped'
    steps:
      - run: exit 1
