name: Trigger Workflow TEST

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: exit 1

  check:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: |
          echo "Test job outcome: ${{ needs.test.result }}"
          if [ "${{ needs.test.result }}" == "failure" ]; then
            echo "Test job failed but was ignored."
          fi
