name: Condition Test Workflow (FAIL)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Trigger Workflow"]
    types:
      - completed

jobs:
  first_job:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]
        shardTotal: [4]
    outputs:
      shard_1: ${{ steps.set_result.outputs.shard_1 }}
      shard_2: ${{ steps.set_result.outputs.shard_2 }}
      shard_3: ${{ steps.set_result.outputs.shard_3 }}
      shard_4: ${{ steps.set_result.outputs.shard_4 }}
    steps:
      - name: Show shard info
        run: echo "Running shard=${{ matrix.shard }} of total=${{ matrix.shardTotal }}"

      - name: Pass or fail shard
        id: pass_or_fail
        run: |
          if [ "${{ matrix.shard }}" = "1" ]; then
            echo "Shard 1 is forced to fail."
            exit 1
          else
            echo "Shard ${{ matrix.shard }} passes."
          fi

      - name: Set outputs per shard
        id: set_result
        run: |
          echo "shard_${{ matrix.shard }}=${{ steps.pass_or_fail.result }}" >> $GITHUB_OUTPUT

  fail_workflow_run_if_tests_failed:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Debug combined outputs
        run: echo '${{ toJSON(needs.first_job.outputs) }}'

      - name: Fail workflow if any shard failed
        run: |
          if [ "${{ needs.first_job.outputs.shard_1 }}" = "failed" ] ||
             [ "${{ needs.first_job.outputs.shard_2 }}" = "failed" ] ||
             [ "${{ needs.first_job.outputs.shard_3 }}" = "failed" ] ||
             [ "${{ needs.first_job.outputs.shard_4 }}" = "failed" ]; then
            echo "At least one shard failed. Exiting with failure."
            exit 1
          fi
