name: Condition Test Workflow (FAIL)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Trigger Workflow"]
    types:
      - completed

jobs:
  first_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        should_fail: [false, true]
    continue-on-error: true
    steps:
      - name: Echo matrix value
        run: echo "This matrix job should_fail=${{ matrix.should_fail }}"
      - name: Pass or fail
        id: playwright-tests
        run: |
          if [ "${{ matrix.should_fail }}" = "true" ]; then
            echo "This job is designed to fail."
            exit 1
          else
            echo "This job is designed to pass."
          fi

  second_job_with_condition:
    needs: first_job
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Run if condition is met
        run: |
            echo "Second job with full condition completed."
            
  fail-this-workflow-if-any-test-failed:
      if: always()
      needs: first_job
      runs-on: ubuntu-latest
      steps:
          - name: Check job conclusion
            run: |
                echo "Job result: ${{ needs.first_job.result }}"
                echo "Job conclusion: ${{ needs.first_job.conclusion }}"
                
                # This is the key - check conclusion vs result
                if [[ "${{ needs.first_job.conclusion }}" == "success" && "${{ needs.first_job.result }}" == "success" ]]; then
                    echo "All tests actually passed"
                else
                    echo "Some tests failed but were ignored due to continue-on-error"
                    exit 1
                fi
