name: Condition Test Workflow (FAIL)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Trigger Workflow"]
    types:
      - completed

jobs:
  first_job:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        should_fail: [false, true]
    outputs:
      shard_${{ matrix.should_fail }}: ${{ steps.set_result.outputs.shard }}
    steps:
      - name: Echo matrix value
        run: echo "This matrix job should_fail=${{ matrix.should_fail }}"

      - name: Pass or fail
        id: pass_or_fail
        run: |
          if [ "${{ matrix.should_fail }}" = "true" ]; then
            echo "This job is designed to fail."
            exit 1
          else
            echo "This job is designed to pass."
          fi

      - name: Set output for shard result
        id: set_result
        run: |
          if [ "${{ steps.pass_or_fail.outcome }}" = "failure" ]; then
            echo "shard=failed" >> $GITHUB_OUTPUT
          else
            echo "shard=passed" >> $GITHUB_OUTPUT
          fi

  second_job_with_condition:
    needs: first_job
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Run if condition is met
        run: |
          echo "Second job with full condition completed."

  fail_workflow_run_if_tests_failed:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Debug combined outputs
        run: echo '${{ toJSON(needs.first_job.outputs) }}'

      - name: Fail workflow if any shard failed
        run: |
          echo "Checking matrix outputs..."
          for shard in "${{ needs.first_job.outputs.shard_false }}" "${{ needs.first_job.outputs.shard_true }}"; do
            echo "Shard result: $shard"
            if [ "$shard" = "failed" ]; then
              echo "At least one shard failed. Failing workflow..."
              exit 1
            fi
          done
